name: 'JSON Version'
description: 'Returns the version key from the specified json file'
branding:
  icon: 'arrow-up'
  color: 'yellow'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  path:
    description: 'The path to the json file'
    required: false
    default: 'package.json'
  compare:
    description: 'The version to compare to against'
    required: false
outputs:
  version:
    description: 'The current version'
  version-diff:
    description: 'The semver diff'
runs:
  using: 'node16'
  main: 'dist/index.js'
